# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WannaBet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WannaBet
pod 'FirebaseUI'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'

  target 'WannaBetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WannaBetUITests' do
    # Pods for testing
  end

end
